### PR TITLE
Pygments

### PR DESCRIPTION
**Pull request by gf3**
Switch over to Pygments for syntax highlighting. Here's an example of what it can look like: http://gf3.ca/2011/02/12/conditional-html-tag-haml

### CODE REVIEW

**Comment by pauldowman** [comment]
Thanks. But why do you like Pygments better? It marks up each element in the HTML, not that that's inherently bad, I guess, but I thought it was kind of nice that SyntaxHighlighter did it all with JavaScript.

**Comment by gf3** [comment]
I wasn't impressed with the quality of SyntaxHighlighter, as well Pygments matches more tokens and a greater array of languages.

**Comment by pauldowman** [comment]
Hmm, it does support a _lot_ more languages and even config file syntaxes. 

It also requires having python and the "pygmentize" script installed, but that might be worth it...

**Comment by pauldowman** [comment]
I'll likely switch to Albino, but I need to do a bit of work on this first, I want to include the pygments script and the css files.

**Comment by gf3** [comment]
Generally it's as easy as `easy_install pygments`

**Pull request closed without merging**
